apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 30s
  chart:
    spec:
      chart: ./charts/nginx
      version: '6.5.*'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30s
  values:
    indexHtml: |-
      <!doctype html>
      <html>
        <head>
          <title>My Custom Page</title>
        </head>
        <body>
          <h1>Welcome to my custom Nginx page!</h1>
        </body>
      </html>
